server:
  port: 8080

spring:
  application:
    name: boot-consumer
  redis:
    host: redis
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
      timeout: 0
    database: 1